name: datitos
channels:
  - pytorch
  - plotly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pylint
  - python-kaleido
  - jupyterlab
  - lame
  - matplotlib
  - mysqlclient
  - numpy
  - optuna
  - pandas
  - pip
  - plotly
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - six
  - tqdm
  - lightgbm
  - pip:
    - optuna-dashboard
    - click
    - imbalanced-learn
