name: datitos
channels:
  - pytorch
  - plotly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pylint
  - python-kaleido
  - jupyterlab
  - lame
  - matplotlib
  - mysqlclient
  - numpy
  - optuna
  - pandas
  - pip
  - plotly
  - pytorch
  - scikit-learn
  - scikit-plot
  - scipy
  - seaborn
  - six
  - tqdm
  - lightgbm
  - util
  - pip:
    - optuna-dashboard
    - click
    - imbalanced-learn
    - jupyterlab_tabnine
    - jupyterlab_execute_time
    - bunch